### ISSUE TITLE
Error in GATK, no definitions in the header

### ISSUE THREAD

**Issue by andreyurch** [mikdio/SOBDetector#1]
Dear developers,

I applied your tool to my VCF file and found that GATK cannot process it anymore because the SOBdetector does not write new definitions to the header:

java.lang.IllegalStateException: Key numF1R2Ref found in VariantContext field INFO at 1:72284 but this key isn't defined in the VCFHeader.  We require all VCFs to have complete VCF headers by default.

**Comment by mikdio** [comment]
Dear andreyurch,
Thanks for the feedback, and sorry for the delay! 
From SOBDetector v1.0.1, the INFO fields are updated in the vcfs.
